// <auto-generated />
namespace GarageWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ConnectionFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConnectionFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201710301207413_ConnectionFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
